M48
; DRILL file {KiCad (6.0.1)} date Mon Feb 28 23:17:04 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-28T23:17:04+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.7327Y-3.4028
X5.9602Y-3.4028
T2
X4.9606Y-3.248
X4.9606Y-5.0197
X6.7323Y-3.248
X6.7323Y-5.0197
T0
M30
